## DocIO

### Bug Fixes
{:#DocIO-bug-fixes}

* \#I473206 - The **IndexOutOfBoundsException** will no longer be thrown while calling `unlink()` API.