## DocIO

### Bug Fixes
{:#DocIO-bug-fixes}

* \#I473206 - The **ArgumentOutOfRangeException** will no longer be thrown while calling `Unlink()` API.